FROM python:3.11-slim

WORKDIR /app
COPY python /app/python

RUN pip install --no-cache-dir fastapi uvicorn[standard]

WORKDIR /app/python
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
